name: deploy

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install tools
              run: npm install

            - name: Build assets
              run: |
                  # echo "module.exports = { plugins: [require('autoprefixer'), require('cssnano')({preset: 'default'})] };" > postcss.config.js
                  npx postcss styles.css -o styles.min.css
                  npx terser script.js -o script.min.js -c -m
                  VERSION=$(date +%s)
                  mv styles.min.css styles.min.$VERSION.css
                  mv script.min.js script.min.$VERSION.js
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Update HTML
              run: |
                  sed -i "s/styles\.css/styles.min.${VERSION}.css/g" index.html
                  sed -i "s/script\.js/script.min.${VERSION}.js/g" index.html

            - name: Generate site folder
              run: |
                  mkdir site
                    cp index.html site/
                    cp styles.min.${VERSION}.css site/
                    cp script.min.${VERSION}.js site/

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: site

    deploy:
        needs: build
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
